name = "VortexDynamics2D"
uuid = "da4b8f6b-df42-4834-94c6-5a2bcb78e49d"
authors = ["Marko <mbudisic@clarkson.edu> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[targets]
test = ["Test"]
